use_frameworks!

target 'ReachabilityView_Example' do
  pod 'ReachabilityView', :path => '../'

  target 'ReachabilityView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
